//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAdminLTE.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoAdminLTE.Resources.Shared.Pages", typeof(Pages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string AccountLogin {
            get {
                return ResourceManager.GetString("AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Profiles.
        /// </summary>
        public static string AccountProfiles {
            get {
                return ResourceManager.GetString("AccountProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string AccountRegistration {
            get {
                return ResourceManager.GetString("AccountRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Logs.
        /// </summary>
        public static string ActivityLogIndex {
            get {
                return ResourceManager.GetString("ActivityLogIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create device.
        /// </summary>
        public static string DeviceCreate {
            get {
                return ResourceManager.GetString("DeviceCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete device.
        /// </summary>
        public static string DeviceDelete {
            get {
                return ResourceManager.GetString("DeviceDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit device.
        /// </summary>
        public static string DeviceEdit {
            get {
                return ResourceManager.GetString("DeviceEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device List.
        /// </summary>
        public static string DeviceIndex {
            get {
                return ResourceManager.GetString("DeviceIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSAdmin.
        /// </summary>
        public static string HomeIndex {
            get {
                return ResourceManager.GetString("HomeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective point-of-sale machine management platform.
        /// </summary>
        public static string HomeIndexDescription {
            get {
                return ResourceManager.GetString("HomeIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create product.
        /// </summary>
        public static string ProductCreate {
            get {
                return ResourceManager.GetString("ProductCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product.
        /// </summary>
        public static string ProductDelete {
            get {
                return ResourceManager.GetString("ProductDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        public static string ProductEdit {
            get {
                return ResourceManager.GetString("ProductEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product list.
        /// </summary>
        public static string ProductIndex {
            get {
                return ResourceManager.GetString("ProductIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new role.
        /// </summary>
        public static string RoleCreate {
            get {
                return ResourceManager.GetString("RoleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete role.
        /// </summary>
        public static string RoleDelete {
            get {
                return ResourceManager.GetString("RoleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role.
        /// </summary>
        public static string RoleEdit {
            get {
                return ResourceManager.GetString("RoleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles list.
        /// </summary>
        public static string RoleIndex {
            get {
                return ResourceManager.GetString("RoleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new sensor.
        /// </summary>
        public static string SensorCreate {
            get {
                return ResourceManager.GetString("SensorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sensor.
        /// </summary>
        public static string SensorDelete {
            get {
                return ResourceManager.GetString("SensorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit sensor.
        /// </summary>
        public static string SensorEdit {
            get {
                return ResourceManager.GetString("SensorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors list.
        /// </summary>
        public static string SensorIndex {
            get {
                return ResourceManager.GetString("SensorIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string StationChart {
            get {
                return ResourceManager.GetString("StationChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new station.
        /// </summary>
        public static string StationCreate {
            get {
                return ResourceManager.GetString("StationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete station.
        /// </summary>
        public static string StationDelete {
            get {
                return ResourceManager.GetString("StationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit station.
        /// </summary>
        public static string StationEdit {
            get {
                return ResourceManager.GetString("StationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations list.
        /// </summary>
        public static string StationIndex {
            get {
                return ResourceManager.GetString("StationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new transaction.
        /// </summary>
        public static string TransactionCreate {
            get {
                return ResourceManager.GetString("TransactionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string TransactionDashboard {
            get {
                return ResourceManager.GetString("TransactionDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete transaction.
        /// </summary>
        public static string TransactionDelete {
            get {
                return ResourceManager.GetString("TransactionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction details.
        /// </summary>
        public static string TransactionDetails {
            get {
                return ResourceManager.GetString("TransactionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit transaction.
        /// </summary>
        public static string TransactionEdit {
            get {
                return ResourceManager.GetString("TransactionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction list.
        /// </summary>
        public static string TransactionIndex {
            get {
                return ResourceManager.GetString("TransactionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        public static string UserCreate {
            get {
                return ResourceManager.GetString("UserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        public static string UserDelete {
            get {
                return ResourceManager.GetString("UserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string UserEdit {
            get {
                return ResourceManager.GetString("UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users list.
        /// </summary>
        public static string UserIndex {
            get {
                return ResourceManager.GetString("UserIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Create.
        /// </summary>
        public static string ValueCreate {
            get {
                return ResourceManager.GetString("ValueCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete value.
        /// </summary>
        public static string ValueDelete {
            get {
                return ResourceManager.GetString("ValueDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit value.
        /// </summary>
        public static string ValueEdit {
            get {
                return ResourceManager.GetString("ValueEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values list.
        /// </summary>
        public static string ValueIndex {
            get {
                return ResourceManager.GetString("ValueIndex", resourceCulture);
            }
        }
    }
}
